sudo: false
dist: trusty
jdk:
  - openjdk8

before_script:
  # Install Buck
  - pushd $HOME
  - git clone --branch v2017.10.01.01 --depth 1 https://github.com/facebook/buck.git
  - cd buck && ant && popd
  - export PATH=$HOME/buck/bin:$PATH
  # Verify Buck installation
  - buck --version

script:
  - buck test //... > /dev/null

services:
  - mongodb

