server:
  port: 8008

cxf:
  contextPath: /personal-details

dao:
  mongo:
    serverAddresses:
      - host: localhost
        port: 27017
    options:
      ssl:
        enabled: false
        invalidHostnameAllowed: false
    dbName: personal-details
    personalDetails:
      name: personalDetails
      username: personalDetailsUser
      password: Passw0rd

kafka:
  url: localhost:9092
  retries: 0
  topic: mongo-updates

---

spring:
  profiles: docker
dao:
  mongo:
    serverAddresses:
      - host: mongo-server
        port: 27017
kafka:
  url: kafka-server:9092