server:
  port: 9009

cxf:
  contextPath: /migration

dao:
  mongo:
    serverAddresses:
      - host: localhost
        port: 27017
    options:
      ssl:
        enabled: false
        invalidHostnameAllowed: false
    dbName: personal-details
    personalDetails:
      name: personalDetails
